{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "chart.fullname" . }}-virtualservice
spec:
  hosts:
{{- range .Values.virtualService.hosts }}
{{- if .enabled }}
  - {{ .domain }}
{{- end }} 
{{- end }}
  gateways:
  - spid-ingress-gateway
  http:
  - match:
    - uri:
        prefix: {{ .Values.virtualService.path | quote }}
    rewrite:
      uri: {{ .Values.virtualService.rewrite | quote }}
    route:
    - destination:
        host: {{ template "chart.fullname" . }}-service.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
{{- end }}
